services:

  app:
    image: analytics-api:v1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8002
    env_file:
      - .env
    ports:
      - "8002:8002" #systemport:dockercontainerappport
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./src:/code:rw
    develop:
      watch:
      - action: rebuild
        path: Dockerfile
      - action: rebuild
        path: requirements.txt
      - action: rebuild
        path: compose.yaml
      
      
    
    
